name: CI
on:
  - push
  - pull_request
env:
  tf_version: 'latest'
  tg_version: 'latest'
  tf_working_dir: 'environments/dev'
jobs:
  Wordpress_on_Minikube:
    runs-on: ubuntu-latest
    name: Wordpress on Minikube
    steps:
    - name: 'Checkout'
      uses: actions/checkout@master
    - name: start minikube
      id: minikube
      uses: medyagh/setup-minikube@master
    - name: export kube/config
      run: kubectl config view --flatten > ~/.kube/config
    - name: 'Terragrunt Init'
      uses: the-commons-project/terragrunt-github-actions@master
      with:
        tf_actions_version: ${{ env.tf_version }}
        tg_actions_version: ${{ env.tg_version }}
        tf_actions_subcommand: 'init'
        tf_actions_working_dir: ${{ env.tf_working_dir }}
        tf_actions_comment: true
    - name: 'Terragrunt Plan'
      uses: the-commons-project/terragrunt-github-actions@master
      with:
        tf_actions_version: ${{ env.tf_version }}
        tg_actions_version: ${{ env.tg_version }}
        tf_actions_subcommand: 'plan'
        tf_actions_working_dir: ${{ env.tf_working_dir }}
        tf_actions_comment: true
    - name: 'Terragrunt Apply'
      uses: the-commons-project/terragrunt-github-actions@master
      with:
        tf_actions_version: ${{ env.tf_version }}
        tg_actions_version: ${{ env.tg_version }}
        tf_actions_subcommand: 'apply'
        tf_actions_working_dir: ${{ env.tf_working_dir }}
        tf_actions_comment: true
    - name: kubectl
      run: kubectl get pods -A -n dev-wordpress --kubeconfig ~/.kube/config
  