name: Deploying Wordpress on Minikube
on:
  - push
  - pull_request
env:
  tf_version: 'latest'
  tg_version: 'latest'
  tf_working_dir: 'environments/dev'
jobs:
  Wordpress_on_Minikube:
    runs-on: ubuntu-latest
    name: Wordpress on Minikube
    steps:
    - name: Install tfenv
      run: git clone https://github.com/tfutils/tfenv.git ~/.tfenv && sudo rm /usr/local/bin/terraform && sudo ln -s ~/.tfenv/bin/* /usr/local/bin
    - name: Install tgenv
      run: git clone https://github.com/cunymatthieu/tgenv.git ~/.tgenv && sudo ln -s ~/.tgenv/bin/* /usr/local/bin
    - name: 'Checkout'
      uses: actions/checkout@master
    - name: Install required Terraform & Terragrunt versions
      run: cd environments && tfenv install && tgenv install
    - name: start minikube
      id: minikube
      uses: medyagh/setup-minikube@master
    - name: enable ingress
      run: minikube addons enable ingress
    - name: removing validation webhook
      run: kubectl delete  validatingwebhookconfigurations ingress-nginx-admission
    - name: 'Terragrunt Init'
      run: cd $tf_working_dir && terragrunt init
    - name: 'Terragrunt Apply'
      run: cd $tf_working_dir && terragrunt apply --auto-approve --input=false
    - name: show running pods
      run: kubectl get pods -n dev-wordpress
    - name: test output
      run: curl --fail --silent -IL $(minikube ip) 2>&1 | grep "HTTP/1.1 200 OK"